### PR TITLE
chore: add note for Hyperloop usage

### PR DESCRIPTION
**Pull request by hansemannn**
cc @janvennemann

### CODE REVIEW

**Comment by janvennemann** [comment]
Wouldn't it be easier to just drop this as a project level hook under `<project-dir>/hooks/ti.swiftsupport.js`? Then the `<plugin>` tag can be left out.

**Comment by hansemannn** [comment]
Didn't know that was possible. What's the deal with plugins then? Also the versioning might be a benefit.

**Comment by janvennemann** [comment]
Versioning indeed might be a benefit. However, this hook was not changed for over a year so i think it's not that important. Also it's pretty small and only one file. For bigger hooks with node dependencies and several modules a plugin may still be a better choice.

**Comment by hansemannn** [comment]
Can you adjust the readme and merge it then?

**Comment by janvennemann** [comment]
Closing in favor of #3

**Pull request closed without merging**
